### ISSUE TITLE
Simbad query often hangs

### ISSUE THREAD

**Issue by BGaensicke** [WD-planets/AstroToolkit#1]
For quite a few objects, the Simbad query that is opened by the Simbad button hangs. This may be the case for all objects where a query for the Gaia source_id does not return a result? E.g. source_id = 404151680911459968. It may be better to query by coordinates, with a search radius that is determined by the proper motions (~5-10" for objects with small / no proper motions, and scaling up the search radius for larger proper motions so that a few decades worth of motion are included).

**Comment by EthanJMoorfield** [comment]
Hi Boris,

This is now fixed with the following functionality:
- Both SIMBAD and Vizier buttons using a Gaia source_id as input now first grab the object's coordinates and use this for the search. In both cases, the chosen radius is also scaled to include any objects up to 1990 (i.e. 26 years worth of proper motion correction compared to Gaia's coordinate epoch of 2016.

Thanks
