### ISSUE TITLE
Check coding structure for image retrieval

### ISSUE THREAD

**Issue by BGaensicke** [WD-planets/AstroToolkit#4]
Minor performance tweak: I noticed that the code looks for SkyMapper images even if it already got a PanSTARRS image. We might want to implement the following priority in getting images: 

1) try PanSTARRS, if that fails
2) try SkyMapper, if that fails
3) fall back to DSS

```
(toolkit) cthulhu:~/Ethan>python datapage_creation.py 
Downloading https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?ra=141.18526027626&dec=8.03089639753&band=g
|==========================================| 896 /896  (100.00%)         0s
Downloading https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?ra=141.18527562554232&dec=8.030882818502223&band=g
|==========================================| 931 /931  (100.00%)         0s
[SkyMapper: SkyMapperGetPhotometryCoords] Note: No SkyMapper data at given coordinates.
amhw: warning: undersampling in frequency
```

**Comment by EthanJMoorfield** [comment]
This isn't actually searching for a SkyMapper image, the hierarchy for image searches matches what you've mentioned above.

That error means that no photometry is being returned from SkyMapper, probably when trying to build an SED etc. 

I definitely need to improve clarity of the errors and am planning to do this soon, I have just been putting it off as I am not sure of the best way to do it since for example, this SkyMapperGetPhotometryCoords can be called from many different tools and so its hard to give meaningful error returns.
